= Contributing to WeeChat scripts
:author: Sébastien Helleu
:email: flashcode@flashtux.org
:lang: en


== Add a script

To submit a new script in this repository, please use the form at:
https://weechat.org/scripts/add/

There are strict rules for new scripts, please read them carefully, otherwise
your script will be rejected.

Pending scripts are visible at: https://weechat.org/scripts/pending/

== Update a script

=== Contact the author

Before updating a script, you *must* contact the author of script directly,
and discuss about your changes (to check if it's OK), especially if you are
adding new features or if you are changing the behavior of the script.

For example, if the author uses a GitHub repository for the script, you can
send a pull request to the author (instead of sending directly to this
repository). +
Then the author will send a pull request on this repository.

=== Security reports

Please *DO NOT* file a GitHub issue for security related problems, but send an
email to <security@weechat.org> instead.

=== Send new release

There are two ways to send a new release for a script:

* Send a pull request (*recommended*). +
  The commit message must have the name of script, version, and changes,
  like that: +
  `script.py 0.3: fix...` +
  Only one script is allowed per pull request.
* Use the form at: <https://weechat.org/scripts/update/> (please use this form
  only if you can not send a pull request).

When sending a new version :

* Don't forget to update the version number in the script (used in `register`
  function) and the ChangeLog (if there is one).
* Do *not* update the author name in script (used in `register` function);
  it must always contain the original script author, even if you are doing
  large updates in the script.
* Python scripts must be compatible with Python 3.x. Support of Python 2.x is
  now optional.

== Report an issue

Before reporting an issue, it's better to contact the author of script
directly.

If you have no answer, or if the author has no time to fix the problem, then
you can report the issue in the tracker (or send an update of script if you are
able to fix yourself).

When reporting an issue, please give the following info:

* Your *WeeChat version*: the output of `/v` in WeeChat, for example:
  _WeeChat 1.7-dev (git: v1.6-6-g997f47f)_.
* If possible, please include a reproducible example: explain the steps which
  led you to the problem.
